"""udate table users

Revision ID: 3318ef2bf36f
Revises: 8ca478274a94
Create Date: 2024-03-27 10:58:16.081383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3318ef2bf36f'
down_revision: Union[str, None] = '8ca478274a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=320), nullable=False))
    op.drop_index('ix_users_user_email', table_name='users')
    op.drop_index('ix_users_user_name', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'user_email')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=False)
    op.create_index('ix_users_user_email', 'users', ['user_email'], unique=True)
    op.drop_column('users', 'email')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
